name: edgedb
description: Official Dart client library for EdgeDB
version: 0.3.0
homepage: https://www.edgedb.com
repository: https://github.com/edgedb/edgedb-dart

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crypto: ^3.0.2
  path: ^1.8.2
  build: ^2.3.0
  code_builder: ^4.2.0
  dart_style: ^2.2.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
